### PR TITLE
create EncumbranceUpdate event

### PR DESCRIPTION
**Pull request by scott-silver**
The OpenZeppelin audit of the Encumber Factory pointed out that there is no event in the EncumberableToken that is emitted when encumbrances are spent.

The IERC7246 spec defines `Encumber` events for when an encumbrance is created and `Release` events for when an encumbrance is released, but no event for when it is spent. These events include the diff between the previous value and the new value, but do not include what the current encumbrance is from the `owner` to the `taker`.

This means that it is not possible to reconstruct an account's current encumbrance state using event logs. For example:

- Alice encumbers 100 tokens to Bob; an `Encumber(alice, bob, 100e18)` event is emitted
- Bob transfers 30 tokens to Charlie; no encumber event is emitted. The Transfer events shows a transfer from Alice to Charlie
- Bob releases 20 encumbered tokens back to Alice; a `Release(alice, bob, 20e18)` event is emitted

Reading the events might give you the false impression that Alice still had 80e18 tokens encumbered to Bob; really her encumbrance balance is 50e18 (100 encumbered - (30 spent + 20 released));

This PR suggests merging the existing events into a single event that can work for encumbering, spending and releasing:

`event EncumbranceUpdate(address indexed owner, address indexed taker, uint256 previousAmount, uint256 newAmount)`

Using the previous example:

- Creating a new encumbrance would emit: `EncumbranceUpdate(alice, bob, 0, 100e18)`
- Spending would emit: `EncumbranceUpdate(alice, bob, 100e18, 70e18)`
- Releasing would emit: `EncumbranceUpdate(alice, bob, 70e18, 50e18)`

You can tell whether an encumbrance is increased or decreased by checking the diff between the two published values. You can tell whether a reduction was caused by a `release` or by a `spend` based on whether it was emitted along with a `Transfer` event. And you can always determine the current encumbrance for an `owner` to `taker` by reading the most recently-emitted event (you don't need to have the full history of events).

### CODE REVIEW

**Review by kevincheng96 — APPROVED** [review]
Looks great! 💪 

For posterity, we are emitting `previousAmount` as part of the event so one can determine whether the encumbrance has increased or decreased without needing to keep track of previous `EncumbranceUpdate` events. 

Another approach discussed was separating out the event into three separate events for `Encumber`, `SpendEncumbrance`, and `Release`.

**Comment by kevincheng96** [comment]
> You can tell whether a reduction was caused by a `release` or by a `spend` based on whether it was emitted along with a `Transfer` event.

Just thought about a case where it's impossible to tell the difference between `release` and `spend` using events.

**Case 1**:
A transfers to B directly
A releases encumbrance to B

**Case 2**:
B spends A's encumbrance to transfer from A to B

In both cases, the events emitted are:
`Transfer(A, B, amount)`
`EncumbranceUpdate(A, B, oldVal, newVal)`

**Comment by mykelp** [comment]
> > You can tell whether a reduction was caused by a `release` or by a `spend` based on whether it was emitted along with a `Transfer` event.
> 
> Just thought about a case where it's impossible to tell the difference between `release` and `spend` using events.
> 
> **Case 1**: A transfers to B directly A releases encumbrance to B
> 
> **Case 2**: B spends A's encumbrance to transfer from A to B
> 
> In both cases, the events emitted are: `Transfer(A, B, amount)` `EncumbranceUpdate(A, B, oldVal, newVal)`

Why would a `release` invoke a transfer? Maybe I'm not understanding correctly but it seems like you are just describing two `SpendEncumbrance` actions?

**Comment by kevincheng96** [comment]
> Why would a `release` invoke a transfer? Maybe I'm not understanding correctly but it seems like you are just describing two `SpendEncumbrance` actions?

Case 1 is user A doing a transfer to B and a release in the same transaction. The transfer emits the `Transfer` event.

**Comment by scott-silver** [comment]
> A transfers to B directly
A releases encumbrance to B

A can't release their own encumbrance to B. It would need to be B calling `release`

**Comment by mykelp** [comment]
spoke with @kevincheng96, and agree that this is an unfortunate edge case. Seems we should consider the splitting of events like we had previously

**Comment by mykelp** [comment]
> > A transfers to B directly
> > A releases encumbrance to B
> 
> A can't release their own encumbrance to B, right? It would need to be B calling `release`

A has 20 tokens, 10 are encumbered to B and 10 are available to transfer. If A transfers 10 tokens to B and then calls release on B, it would appear from the events that this as a `SpendEncumbrance`. It's definitely a low probability edge case, but still unsettling that it's possible.

**Comment by scott-silver** [comment]
The 10 tokens that A has encumbered to B can only be released by B.

**Comment by mykelp** [comment]
> The 10 tokens that A has encumbered to B can only be released by B.

yes, the scenario described above transfers the 10 free tokens and then asks B to release 10 encumbered tokens. The emitting of the events looks like a `SpendEncumbrance` when technically it was a `Release`

**Comment by scott-silver** [comment]
Ah, gotcha. You would have to ask B to release the encumbrance, which is plausible.

So should we go with three events?

```
 event Encumber(address indexed owner, address indexed taker, uint amount);

event Release(address indexed owner, address indexed taker, uint amount);

event SpendEncumbrance(address indexed owner, address indexed taker, uint amount);
```

And should `amount` be the current encumbrance from owner to taker? Or the diff from the last update?

**Comment by kevincheng96** [comment]
> And should `amount` be the current encumbrance from owner to taker? Or the diff from the last update?

I think diff makes more sense in that case. I don't see a strong reason to emit the current encumbrance, just like how a `Transfer` event does not emit the current balance.

**Comment by scott-silver** [comment]
Closing this PR; will open a new PR with a third Encumbrance event

**Pull request closed without merging**
