### PR TITLE
Pre-audit updates

### PR DESCRIPTION
**Pull request by scott-silver**
working through some pre-audit feedback:

> Non-explicit imports are used

> State variable visibility not explicitly declared

> Missing docstrings

> Unused import

> Using int/uint instead of int256/uint256

> Constant not using UPPER_CASE format

### CODE REVIEW

**Review by kevincheng96 — APPROVED** [review]
Looks good! 

Thoughts on moving towards non-explicit imports?

**Comment by scott-silver** [comment]
> Thoughts on moving towards non-explicit imports?

I don't have strong feelings about them. I suppose it would be an improvement to be explicit about what we're importing.

**Comment by scott-silver** [comment]
updated to use explicit imports.

the only import that i was unable to convert to an explicit import is `import "forge-std/StdUtils.sol";`, which we use to import Forge's [ERC20 `deal` function](https://book.getfoundry.sh/cheatcodes/deal)

**Review by kevincheng96 — APPROVED** [review]
🔥

**Pull request merged**
